version: '3.8'

services:
  # api:
  #   build: 
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./api:/app
  #     # Mount model files
  #     - ./models/age_regression.pt:/app/models/age_regression.pt
  #     - ./models/gender_classification.pt:/app/models/gender_classification.pt
  #   depends_on:
  #     - db
  #   networks:
  #     - app_network

  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=GARSDB
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge